name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  validity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run example
        run: |
          cargo run -F inline-source-map --example source_map_creation -- LICENSE LICENSE.map
          echo "### Input
          \`\`\`
          $(cat LICENSE)
          \`\`\`
          
          ### Output
          \`\`\`
          $(cat LICENSE.map)
          \`\`\`
          " >> >> $GITHUB_STEP_SUMMARY